# condutas.py

CONDUTAS = {'cisto_radicular': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                     'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                     'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                     'urgencia': 'baixa a moderada'},
 'cisto_residual': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                    'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                    'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                    'urgencia': 'baixa a moderada'},
 'cisto_dentigero': {'procedimento': 'avaliação cirúrgica; enucleação/marsupialização conforme tamanho, idade e '
                                     'relação anatômica',
                     'exames': 'CBCT para extensão e relação com dente incluso; teste de vitalidade quando houver '
                               'dentes adjacentes',
                     'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                     'urgencia': 'baixa a moderada'},
 'queratocisto_odontogenico': {'procedimento': 'avaliação cirúrgica; enucleação/marsupialização conforme tamanho, '
                                               'idade e relação anatômica',
                               'exames': 'CBCT para extensão e relação com dente incluso; teste de vitalidade quando '
                                         'houver dentes adjacentes',
                               'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                               'urgencia': 'baixa a moderada'},
 'cisto_periodontal_lateral': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                               'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                               'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                               'urgencia': 'baixa a moderada'},
 'cisto_botrioide': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                     'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                     'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                     'urgencia': 'baixa a moderada'},
 'cisto_odontogenico_calcificante': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                                     'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                                     'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                     'urgencia': 'baixa a moderada'},
 'cisto_gengival_adulto': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                           'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                           'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                           'urgencia': 'baixa a moderada'},
 'cisto_inflamatorio_colateral': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                                  'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                                  'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                  'urgencia': 'baixa a moderada'},
 'cisto_ciliado_cirurgico': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                             'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                             'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                             'urgencia': 'baixa a moderada'},
 'ameloblastoma_convencional': {'procedimento': 'biópsia incisional se lesão extensa; planejamento cirúrgico após '
                                                'confirmação',
                                'exames': 'CBCT para extensão, corticais, canal mandibular e reabsorção radicular',
                                'encaminhamento': 'Cirurgia Bucomaxilofacial e Patologia Oral',
                                'urgencia': 'moderada'},
 'ameloblastoma_unicistico': {'procedimento': 'avaliação cirúrgica; enucleação/marsupialização conforme tamanho, idade '
                                              'e relação anatômica',
                              'exames': 'CBCT para extensão e relação com dente incluso; teste de vitalidade quando '
                                        'houver dentes adjacentes',
                              'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                              'urgencia': 'baixa a moderada'},
 'tumor_odontogenico_adenomatoide': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                                     'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                                     'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                     'urgencia': 'baixa a moderada'},
 'tumor_epitelial_odontogenico_calcificante': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme '
                                                               'extensão',
                                               'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                                               'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                               'urgencia': 'baixa a moderada'},
 'tumor_odontogenico_escamoso': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                                 'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                                 'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                 'urgencia': 'baixa a moderada'},
 'mixoma_odontogenico': {'procedimento': 'biópsia incisional se lesão extensa; planejamento cirúrgico após confirmação',
                         'exames': 'CBCT para extensão, corticais, canal mandibular e reabsorção radicular',
                         'encaminhamento': 'Cirurgia Bucomaxilofacial e Patologia Oral',
                         'urgencia': 'moderada'},
 'fibroma_odontogenico_central': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                                  'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                                  'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                  'urgencia': 'baixa a moderada'},
 'cementoblastoma': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                     'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                     'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                     'urgencia': 'baixa a moderada'},
 'odontoma_composto': {'procedimento': 'excisão cirúrgica conservadora/enucleação quando indicado',
                       'exames': 'radiografia panorâmica/periapical e CBCT para relação com dentes inclusos e '
                                 'estruturas anatômicas',
                       'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                       'urgencia': 'baixa'},
 'odontoma_complexo': {'procedimento': 'excisão cirúrgica conservadora/enucleação quando indicado',
                       'exames': 'radiografia panorâmica/periapical e CBCT para relação com dentes inclusos e '
                                 'estruturas anatômicas',
                       'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                       'urgencia': 'baixa'},
 'tumor_odontogenico_primordial': {'procedimento': 'avaliação cirúrgica; enucleação/marsupialização conforme tamanho, '
                                                   'idade e relação anatômica',
                                   'exames': 'CBCT para extensão e relação com dente incluso; teste de vitalidade '
                                             'quando houver dentes adjacentes',
                                   'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                   'urgencia': 'baixa a moderada'},
 'carcinoma_ameloblastico': {'procedimento': 'biópsia incisional prioritária e investigação sistêmica quando indicada',
                             'exames': 'CBCT/TC; RM se partes moles; avaliação médica/oncológica conforme suspeita',
                             'encaminhamento': 'Cirurgia Bucomaxilofacial, Patologia Oral e serviço médico '
                                               'especializado',
                             'urgencia': 'alta'},
 'carcinoma_intraosseo_primario': {'procedimento': 'biópsia incisional prioritária e investigação sistêmica quando '
                                                   'indicada',
                                   'exames': 'CBCT/TC; RM se partes moles; avaliação médica/oncológica conforme '
                                             'suspeita',
                                   'encaminhamento': 'Cirurgia Bucomaxilofacial, Patologia Oral e serviço médico '
                                                     'especializado',
                                   'urgencia': 'alta'},
 'carcinoma_odontogenico_esclerosante': {'procedimento': 'biópsia incisional prioritária e investigação sistêmica '
                                                         'quando indicada',
                                         'exames': 'CBCT/TC; RM se partes moles; avaliação médica/oncológica conforme '
                                                   'suspeita',
                                         'encaminhamento': 'Cirurgia Bucomaxilofacial, Patologia Oral e serviço médico '
                                                           'especializado',
                                         'urgencia': 'alta'},
 'carcinoma_odontogenico_celulas_claras': {'procedimento': 'biópsia incisional prioritária e investigação sistêmica '
                                                           'quando indicada',
                                           'exames': 'CBCT/TC; RM se partes moles; avaliação médica/oncológica '
                                                     'conforme suspeita',
                                           'encaminhamento': 'Cirurgia Bucomaxilofacial, Patologia Oral e serviço '
                                                             'médico especializado',
                                           'urgencia': 'alta'},
 'sarcoma_odontogenico': {'procedimento': 'biópsia incisional prioritária e investigação sistêmica quando indicada',
                          'exames': 'CBCT/TC; RM se partes moles; avaliação médica/oncológica conforme suspeita',
                          'encaminhamento': 'Cirurgia Bucomaxilofacial, Patologia Oral e serviço médico especializado',
                          'urgencia': 'alta'},
 'displasia_fibrosa': {'procedimento': 'correlação clínico-radiográfica; acompanhamento ou abordagem cirúrgica se '
                                       'expansão/sintomas',
                       'exames': 'radiografias seriadas e CBCT quando necessário',
                       'encaminhamento': 'Estomatologia/Radiologia Odontológica',
                       'urgencia': 'baixa'},
 'fibroma_ossificante': {'procedimento': 'correlação clínico-radiográfica; acompanhamento ou abordagem cirúrgica se '
                                         'expansão/sintomas',
                         'exames': 'radiografias seriadas e CBCT quando necessário',
                         'encaminhamento': 'Estomatologia/Radiologia Odontológica',
                         'urgencia': 'baixa'},
 'displasia_cemento_ossea_focal': {'procedimento': 'correlação clínico-radiográfica; acompanhamento ou abordagem '
                                                   'cirúrgica se expansão/sintomas',
                                   'exames': 'radiografias seriadas e CBCT quando necessário',
                                   'encaminhamento': 'Estomatologia/Radiologia Odontológica',
                                   'urgencia': 'baixa'},
 'displasia_cemento_ossea_florida': {'procedimento': 'correlação clínico-radiográfica; acompanhamento ou abordagem '
                                                     'cirúrgica se expansão/sintomas',
                                     'exames': 'radiografias seriadas e CBCT quando necessário',
                                     'encaminhamento': 'Estomatologia/Radiologia Odontológica',
                                     'urgencia': 'baixa'},
 'granuloma_central_celulas_gigantes': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                                        'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                                        'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                        'urgencia': 'baixa a moderada'},
 'cisto_osseo_simples': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                         'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                         'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                         'urgencia': 'baixa a moderada'},
 'cisto_osseo_aneurismatico': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                               'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                               'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                               'urgencia': 'baixa a moderada'},
 'osteomielite_cronica': {'procedimento': 'controle infeccioso, remoção de fator causal quando possível e avaliação '
                                          'especializada',
                          'exames': 'CBCT; hemograma/PCR quando infecção; revisão medicamentosa',
                          'encaminhamento': 'Cirurgia Bucomaxilofacial/Estomatologia',
                          'urgencia': 'moderada'},
 'osteonecrose_medicamentosa': {'procedimento': 'controle infeccioso, remoção de fator causal quando possível e '
                                                'avaliação especializada',
                                'exames': 'CBCT; hemograma/PCR quando infecção; revisão medicamentosa',
                                'encaminhamento': 'Cirurgia Bucomaxilofacial/Estomatologia',
                                'urgencia': 'moderada'},
 'tumor_marrom_hiperparatireoidismo': {'procedimento': 'investigação metabólica antes de abordagem local',
                                       'exames': 'cálcio, fósforo, PTH, função renal e avaliação médica',
                                       'encaminhamento': 'Endocrinologia/Nefrologia e Estomatologia',
                                       'urgencia': 'moderada'},
 'metastase_ossea_gnatica': {'procedimento': 'biópsia incisional prioritária e investigação sistêmica quando indicada',
                             'exames': 'CBCT/TC; RM se partes moles; avaliação médica/oncológica conforme suspeita',
                             'encaminhamento': 'Cirurgia Bucomaxilofacial, Patologia Oral e serviço médico '
                                               'especializado',
                             'urgencia': 'alta'},
 'mieloma_multiplo': {'procedimento': 'biópsia incisional prioritária e investigação sistêmica quando indicada',
                      'exames': 'CBCT/TC; RM se partes moles; avaliação médica/oncológica conforme suspeita',
                      'encaminhamento': 'Cirurgia Bucomaxilofacial, Patologia Oral e serviço médico especializado',
                      'urgencia': 'alta'},
 'linfoma_osseo': {'procedimento': 'biópsia incisional prioritária e investigação sistêmica quando indicada',
                   'exames': 'CBCT/TC; RM se partes moles; avaliação médica/oncológica conforme suspeita',
                   'encaminhamento': 'Cirurgia Bucomaxilofacial, Patologia Oral e serviço médico especializado',
                   'urgencia': 'alta'},
 'defeito_osseo_stafne': {'procedimento': 'sem biópsia em caso típico; acompanhamento radiográfico ou CBCT para '
                                          'confirmação',
                          'exames': 'CBCT para confirmar depressão lingual abaixo do canal mandibular',
                          'encaminhamento': 'Radiologia Odontológica/Estomatologia se dúvida',
                          'urgencia': 'baixa'},
 'histiocitose_celulas_langerhans': {'procedimento': 'avaliação clínico-radiográfica e conduta conforme extensão',
                                     'exames': 'radiografia/CBCT e testes dentários quando aplicáveis',
                                     'encaminhamento': 'Estomatologia ou Cirurgia Bucomaxilofacial',
                                     'urgencia': 'baixa a moderada'}}
