# perfis_diagnosticos.py
# Perfis semiológicos para ajuste pós-modelo em lesões intraósseas odontogênicas e diferenciais.
# Campos esperados em achados: dicionário {nome_do_achado: bool}.

PERFIS_DIAGNOSTICOS = {'cisto_radicular': {'grupo': 'cisto_odontogenico_inflamatorio',
                     'necessarios': ['radiolucido', 'periapical'],
                     'fortes': ['dente_nao_vital', 'bem_delimitado', 'corticalizado', 'unilocular', 'halo_esclerotico'],
                     'moderados': ['assintomatico', 'dor_leve', 'fistula', 'historia_carie_ou_trauma'],
                     'incompativeis': ['dente_vital',
                                       'estruturas_dentiformes',
                                       'radiopaco_puro',
                                       'margem_mal_definida',
                                       'parestesia'],
                     'score_malignidade_esperado': 'muito_baixo'},
 'cisto_residual': {'grupo': 'cisto_odontogenico_inflamatorio',
                    'necessarios': ['radiolucido', 'area_edentula'],
                    'fortes': ['bem_delimitado', 'corticalizado', 'unilocular', 'historia_extracao'],
                    'moderados': ['assintomatico', 'mandibula_posterior', 'maxila_posterior'],
                    'incompativeis': ['dente_associado_presente',
                                      'estruturas_dentiformes',
                                      'radiopaco_puro',
                                      'margem_mal_definida',
                                      'parestesia'],
                    'score_malignidade_esperado': 'muito_baixo'},
 'cisto_dentigero': {'grupo': 'cisto_odontogenico_desenvolvimento',
                     'necessarios': ['radiolucido', 'pericoronario', 'dente_incluso'],
                     'fortes': ['unilocular', 'bem_delimitado', 'corticalizado', 'halo_pericoronario', 'assintomatico'],
                     'moderados': ['paciente_jovem', 'terceiro_molar_incluso', 'canino_incluso', 'expansao_discreta'],
                     'incompativeis': ['estruturas_dentiformes',
                                       'radiopaco_puro',
                                       'margem_mal_definida',
                                       'destruicao_cortical',
                                       'parestesia'],
                     'score_malignidade_esperado': 'muito_baixo'},
 'queratocisto_odontogenico': {'grupo': 'cisto_odontogenico_desenvolvimento',
                               'necessarios': ['radiolucido'],
                               'fortes': ['posterior_mandibula',
                                          'crescimento_anteroposterior',
                                          'pouca_expansao',
                                          'bem_delimitado',
                                          'corticalizado',
                                          'unilocular'],
                               'moderados': ['multilocular', 'ramo_mandibular', 'recorrente', 'dente_incluso'],
                               'incompativeis': ['radiopaco_puro',
                                                 'estruturas_dentiformes',
                                                 'vidro_fosco',
                                                 'dor_intensa',
                                                 'destruicao_cortical_difusa'],
                               'score_malignidade_esperado': 'baixo'},
 'cisto_periodontal_lateral': {'grupo': 'cisto_odontogenico_desenvolvimento',
                               'necessarios': ['radiolucido', 'interradicular', 'dente_vital'],
                               'fortes': ['pequeno_5_10mm',
                                          'unilocular',
                                          'bem_delimitado',
                                          'corticalizado',
                                          'assintomatico'],
                               'moderados': ['mandibula_premolar', 'lateral_radicular', 'sem_expansao'],
                               'incompativeis': ['dente_nao_vital',
                                                 'grande_maior_40mm',
                                                 'multilocular',
                                                 'destruicao_cortical',
                                                 'radiopaco_puro'],
                               'score_malignidade_esperado': 'muito_baixo'},
 'cisto_botrioide': {'grupo': 'cisto_odontogenico_desenvolvimento',
                     'necessarios': ['radiolucido', 'interradicular', 'dente_vital'],
                     'fortes': ['multilocular', 'bem_delimitado', 'mandibula_premolar', 'assintomatico'],
                     'moderados': ['pequeno_10_20mm', 'lobulado', 'recorrente'],
                     'incompativeis': ['dente_nao_vital', 'radiopaco_puro', 'destruicao_cortical', 'parestesia'],
                     'score_malignidade_esperado': 'baixo'},
 'cisto_odontogenico_calcificante': {'grupo': 'cisto_odontogenico_desenvolvimento',
                                     'necessarios': ['radiolucido_ou_misto'],
                                     'fortes': ['calcificacoes_internas',
                                                'bem_delimitado',
                                                'unilocular',
                                                'dente_incluso',
                                                'anterior_maxila'],
                                     'moderados': ['expansao_discreta', 'paciente_jovem', 'halo_radiolucido'],
                                     'incompativeis': ['radiopaco_puro_sem_halo',
                                                       'margem_mal_definida',
                                                       'destruicao_cortical',
                                                       'parestesia'],
                                     'score_malignidade_esperado': 'baixo'},
 'cisto_gengival_adulto': {'grupo': 'cisto_odontogenico_extraosseo',
                           'necessarios': ['lesao_mucosa_gengival', 'dente_vital'],
                           'fortes': ['pequeno_ate_5mm',
                                      'assintomatico',
                                      'gengiva_canino_premolar',
                                      'sem_alteracao_ossea'],
                           'moderados': ['nodulo_azulado', 'mucosa_normal'],
                           'incompativeis': ['intraosseo_extenso',
                                             'grande_maior_40mm',
                                             'multilocular',
                                             'destruicao_cortical'],
                           'score_malignidade_esperado': 'muito_baixo'},
 'cisto_inflamatorio_colateral': {'grupo': 'cisto_odontogenico_inflamatorio',
                                  'necessarios': ['radiolucido', 'lateral_radicular'],
                                  'fortes': ['terceiro_molar_parcialmente_erupcionado',
                                             'pericoronarite',
                                             'mandibula_posterior',
                                             'bem_delimitado'],
                                  'moderados': ['dor_leve', 'edema_local', 'dente_vital'],
                                  'incompativeis': ['radiopaco_puro',
                                                    'estruturas_dentiformes',
                                                    'margem_mal_definida',
                                                    'parestesia'],
                                  'score_malignidade_esperado': 'muito_baixo'},
 'cisto_ciliado_cirurgico': {'grupo': 'cisto_nao_odontogenico_maxila',
                             'necessarios': ['radiolucido', 'maxila_posterior'],
                             'fortes': ['historia_cirurgia_seio_maxilar',
                                        'relacao_seio_maxilar',
                                        'bem_delimitado',
                                        'unilocular'],
                             'moderados': ['expansao_discreta', 'dor_leve', 'adulto'],
                             'incompativeis': ['mandibula',
                                               'estruturas_dentiformes',
                                               'radiopaco_puro',
                                               'abaixo_canal_mandibular'],
                             'score_malignidade_esperado': 'baixo'},
 'ameloblastoma_convencional': {'grupo': 'tumor_odontogenico_benigno_agressivo',
                                'necessarios': ['radiolucido'],
                                'fortes': ['multilocular',
                                           'bolhas_de_sabao',
                                           'posterior_mandibula',
                                           'expansao_cortical',
                                           'expansao_bicortical',
                                           'reabsorcao_radicular'],
                                'moderados': ['crescimento_lento',
                                              'adulto_jovem',
                                              'assimetria_facial',
                                              'deslocamento_dentario'],
                                'incompativeis': ['radiopaco_puro',
                                                  'estruturas_dentiformes',
                                                  'abaixo_canal_mandibular_sem_expansao',
                                                  'sem_expansao'],
                                'score_malignidade_esperado': 'baixo_intermediario'},
 'ameloblastoma_unicistico': {'grupo': 'tumor_odontogenico_benigno_agressivo',
                              'necessarios': ['radiolucido', 'unilocular'],
                              'fortes': ['pericoronario',
                                         'dente_incluso',
                                         'paciente_jovem',
                                         'mandibula_posterior',
                                         'expansao_cortical'],
                              'moderados': ['reabsorcao_radicular', 'corticalizado', 'crescimento_lento'],
                              'incompativeis': ['radiopaco_puro',
                                                'estruturas_dentiformes',
                                                'margem_mal_definida',
                                                'lesoes_multiplas'],
                              'score_malignidade_esperado': 'baixo'},
 'tumor_odontogenico_adenomatoide': {'grupo': 'tumor_odontogenico_benigno',
                                     'necessarios': ['radiolucido_ou_misto', 'dente_incluso'],
                                     'fortes': ['anterior_maxila',
                                                'canino_incluso',
                                                'calcificacoes_finas',
                                                'bem_delimitado',
                                                'pericoronario'],
                                     'moderados': ['paciente_jovem', 'sexo_feminino', 'assintomatico', 'unilocular'],
                                     'incompativeis': ['posterior_mandibula_extensa',
                                                       'multilocular_agressivo',
                                                       'margem_mal_definida',
                                                       'destruicao_cortical'],
                                     'score_malignidade_esperado': 'muito_baixo'},
 'tumor_epitelial_odontogenico_calcificante': {'grupo': 'tumor_odontogenico_benigno',
                                               'necessarios': ['radiolucido_ou_misto'],
                                               'fortes': ['calcificacoes_internas',
                                                          'driven_snow',
                                                          'dente_incluso',
                                                          'posterior_mandibula',
                                                          'expansao_cortical'],
                                               'moderados': ['bem_delimitado', 'adulto', 'misto'],
                                               'incompativeis': ['estruturas_dentiformes',
                                                                 'radiolucido_puro_sem_calcificacao',
                                                                 'margem_mal_definida'],
                                               'score_malignidade_esperado': 'baixo'},
 'tumor_odontogenico_escamoso': {'grupo': 'tumor_odontogenico_benigno',
                                 'necessarios': ['radiolucido', 'interradicular'],
                                 'fortes': ['defeito_semilunar',
                                            'dentes_vitais',
                                            'bem_delimitado',
                                            'mobilidade_dentaria'],
                                 'moderados': ['adulto', 'anterior_maxila', 'mandibula_posterior'],
                                 'incompativeis': ['pericoronario',
                                                   'estruturas_dentiformes',
                                                   'radiopaco_puro',
                                                   'grande_maior_40mm'],
                                 'score_malignidade_esperado': 'baixo'},
 'mixoma_odontogenico': {'grupo': 'tumor_odontogenico_benigno_agressivo',
                         'necessarios': ['radiolucido'],
                         'fortes': ['multilocular',
                                    'raquete_de_tenis',
                                    'septacoes_finas',
                                    'expansao_cortical',
                                    'posterior_mandibula'],
                         'moderados': ['crescimento_lento',
                                       'adulto_jovem',
                                       'deslocamento_dentario',
                                       'zona_transicao_intermediaria'],
                         'incompativeis': ['radiopaco_puro', 'estruturas_dentiformes', 'periapical_dente_nao_vital'],
                         'score_malignidade_esperado': 'baixo_intermediario'},
 'fibroma_odontogenico_central': {'grupo': 'tumor_odontogenico_benigno',
                                  'necessarios': ['radiolucido'],
                                  'fortes': ['bem_delimitado',
                                             'unilocular_ou_multilocular',
                                             'expansao_discreta',
                                             'deslocamento_dentario'],
                                  'moderados': ['adulto', 'mandibula_posterior', 'corticalizado'],
                                  'incompativeis': ['radiopaco_puro',
                                                    'margem_mal_definida',
                                                    'destruicao_cortical',
                                                    'estruturas_dentiformes'],
                                  'score_malignidade_esperado': 'baixo'},
 'cementoblastoma': {'grupo': 'tumor_odontogenico_benigno',
                     'necessarios': ['radiopaco_ou_misto', 'fusionado_raiz'],
                     'fortes': ['halo_radiolucido',
                                'dor_leve',
                                'expansao_cortical',
                                'mandibula_molar',
                                'reabsorcao_radicular'],
                     'moderados': ['paciente_jovem', 'dente_vital', 'massa_radiopaca'],
                     'incompativeis': ['sem_relacao_raiz',
                                       'estruturas_dentiformes',
                                       'margem_mal_definida',
                                       'lesoes_multiplas'],
                     'score_malignidade_esperado': 'baixo'},
 'odontoma_composto': {'grupo': 'hamartoma_odontogenico',
                       'necessarios': ['radiopaco_ou_misto', 'estruturas_dentiformes'],
                       'fortes': ['multiplas_estruturas_dentiformes',
                                  'halo_radiolucido',
                                  'anterior_maxila',
                                  'dente_incluso',
                                  'assintomatico'],
                       'moderados': ['paciente_jovem', 'retencao_dentaria', 'bem_delimitado'],
                       'incompativeis': ['radiolucido_puro',
                                         'margem_mal_definida',
                                         'destruicao_cortical',
                                         'parestesia',
                                         'crescimento_rapido'],
                       'score_malignidade_esperado': 'muito_baixo'},
 'odontoma_complexo': {'grupo': 'hamartoma_odontogenico',
                       'necessarios': ['radiopaco_ou_misto'],
                       'fortes': ['massa_radiopaca_irregular',
                                  'halo_radiolucido',
                                  'dente_incluso',
                                  'bem_delimitado',
                                  'assintomatico'],
                       'moderados': ['posterior_mandibula', 'posterior_maxila', 'retencao_dentaria', 'paciente_jovem'],
                       'incompativeis': ['radiolucido_puro',
                                         'margem_mal_definida',
                                         'destruicao_cortical',
                                         'parestesia',
                                         'crescimento_rapido'],
                       'score_malignidade_esperado': 'muito_baixo'},
 'tumor_odontogenico_primordial': {'grupo': 'tumor_odontogenico_benigno_raro',
                                   'necessarios': ['radiolucido', 'pericoronario', 'dente_incluso'],
                                   'fortes': ['paciente_crianca_adolescente',
                                              'posterior_mandibula',
                                              'bem_delimitado',
                                              'unilocular',
                                              'expansao_cortical'],
                                   'moderados': ['crescimento_lento', 'deslocamento_dentario', 'assintomatico'],
                                   'incompativeis': ['radiopaco_puro',
                                                     'estruturas_dentiformes',
                                                     'adulto_idoso',
                                                     'margem_mal_definida'],
                                   'score_malignidade_esperado': 'baixo'},
 'carcinoma_ameloblastico': {'grupo': 'maligna_odontogenica',
                             'necessarios': [],
                             'fortes': ['radiolucido',
                                        'multilocular',
                                        'margem_mal_definida',
                                        'destruicao_cortical',
                                        'dor_intensa',
                                        'crescimento_rapido',
                                        'parestesia'],
                             'moderados': ['posterior_mandibula', 'invasao_partes_moles', 'reabsorcao_radicular'],
                             'incompativeis': ['assintomatico_sem_sinais_agressivos',
                                               'bem_delimitado_corticalizado',
                                               'estruturas_dentiformes'],
                             'score_malignidade_esperado': 'alto'},
 'carcinoma_intraosseo_primario': {'grupo': 'maligna_odontogenica',
                                   'necessarios': [],
                                   'fortes': ['radiolucido',
                                              'margem_mal_definida',
                                              'destruicao_cortical',
                                              'dor_intensa',
                                              'parestesia',
                                              'mobilidade_dentaria'],
                                   'moderados': ['idade_maior_50', 'crescimento_rapido', 'invasao_partes_moles'],
                                   'incompativeis': ['estruturas_dentiformes',
                                                     'radiopaco_puro_com_halo',
                                                     'bem_delimitado_corticalizado',
                                                     'assintomatico'],
                                   'score_malignidade_esperado': 'alto'},
 'carcinoma_odontogenico_esclerosante': {'grupo': 'maligna_odontogenica',
                                         'necessarios': [],
                                         'fortes': ['margem_mal_definida',
                                                    'radiolucido_ou_misto',
                                                    'destruicao_cortical',
                                                    'parestesia',
                                                    'dor_intensa'],
                                         'moderados': ['adulto', 'mandibula_posterior', 'infiltrativo'],
                                         'incompativeis': ['estruturas_dentiformes',
                                                           'bem_delimitado_corticalizado',
                                                           'assintomatico_sem_sinais_agressivos'],
                                         'score_malignidade_esperado': 'alto'},
 'carcinoma_odontogenico_celulas_claras': {'grupo': 'maligna_odontogenica',
                                           'necessarios': [],
                                           'fortes': ['radiolucido',
                                                      'margem_mal_definida',
                                                      'destruicao_cortical',
                                                      'parestesia',
                                                      'dor_intensa'],
                                           'moderados': ['mulher_adulta', 'mandibula', 'mobilidade_dentaria'],
                                           'incompativeis': ['estruturas_dentiformes',
                                                             'radiopaco_puro_com_halo',
                                                             'bem_delimitado_corticalizado',
                                                             'paciente_crianca_adolescente'],
                                           'score_malignidade_esperado': 'alto'},
 'sarcoma_odontogenico': {'grupo': 'maligna_odontogenica',
                          'necessarios': [],
                          'fortes': ['crescimento_rapido',
                                     'margem_mal_definida',
                                     'destruicao_cortical',
                                     'dor_intensa',
                                     'invasao_partes_moles'],
                          'moderados': ['jovem_adulto', 'radiolucido_ou_misto', 'parestesia'],
                          'incompativeis': ['bem_delimitado_corticalizado', 'assintomatico', 'estruturas_dentiformes'],
                          'score_malignidade_esperado': 'alto'},
 'displasia_fibrosa': {'grupo': 'fibro_ossea',
                       'necessarios': ['vidro_fosco'],
                       'fortes': ['margens_imprecisas',
                                  'expansao_fusiforme',
                                  'maxila',
                                  'paciente_jovem',
                                  'radiopaco_ou_misto'],
                       'moderados': ['assimetria_facial', 'sem_dor', 'continuidade_osso'],
                       'incompativeis': ['halo_radiolucido',
                                         'estruturas_dentiformes',
                                         'periapical_dente_nao_vital',
                                         'margem_mal_definida_destrutiva'],
                       'score_malignidade_esperado': 'baixo'},
 'fibroma_ossificante': {'grupo': 'fibro_ossea',
                         'necessarios': ['bem_delimitado'],
                         'fortes': ['radiolucido_ou_misto',
                                    'halo_esclerotico',
                                    'expansao_cortical',
                                    'mandibula_premolar_molar',
                                    'mulher_adulta'],
                         'moderados': ['crescimento_lento', 'deslocamento_dentario', 'calcificacoes_internas'],
                         'incompativeis': ['vidro_fosco_difuso_sem_limite',
                                           'margem_mal_definida',
                                           'destruicao_cortical',
                                           'estruturas_dentiformes'],
                         'score_malignidade_esperado': 'baixo'},
 'displasia_cemento_ossea_focal': {'grupo': 'fibro_ossea',
                                   'necessarios': ['periapical_ou_edentula'],
                                   'fortes': ['radiolucido_ou_misto',
                                              'mandibula_posterior',
                                              'mulher_adulta',
                                              'dente_vital',
                                              'assintomatico'],
                                   'moderados': ['pequeno_10_20mm', 'halo_radiolucido', 'evolucao_radiopaca'],
                                   'incompativeis': ['dente_nao_vital',
                                                     'grande_maior_40mm',
                                                     'expansao_importante',
                                                     'parestesia'],
                                   'score_malignidade_esperado': 'muito_baixo'},
 'displasia_cemento_ossea_florida': {'grupo': 'fibro_ossea',
                                     'necessarios': ['lesoes_multiplas', 'bilateral'],
                                     'fortes': ['radiopaco_ou_misto',
                                                'mandibula',
                                                'mulher_adulta',
                                                'dentes_vitais',
                                                'assintomatico'],
                                     'moderados': ['simetrico', 'periapical_multifocal', 'descoberta_incidental'],
                                     'incompativeis': ['lesao_unica_pequena',
                                                       'dente_nao_vital_unico',
                                                       'estruturas_dentiformes',
                                                       'margem_mal_definida_destrutiva'],
                                     'score_malignidade_esperado': 'muito_baixo'},
 'granuloma_central_celulas_gigantes': {'grupo': 'lesao_osteolitica_benigna',
                                        'necessarios': ['radiolucido'],
                                        'fortes': ['anterior_mandibula',
                                                   'cruza_linha_media',
                                                   'multilocular',
                                                   'expansao_cortical',
                                                   'paciente_jovem'],
                                        'moderados': ['deslocamento_dentario',
                                                      'reabsorcao_radicular',
                                                      'assintomatico_ou_dor_leve'],
                                        'incompativeis': ['radiopaco_puro',
                                                          'estruturas_dentiformes',
                                                          'periapical_dente_nao_vital'],
                                        'score_malignidade_esperado': 'baixo_intermediario'},
 'cisto_osseo_simples': {'grupo': 'pseudocisto',
                         'necessarios': ['radiolucido'],
                         'fortes': ['scalloped_entre_raizes',
                                    'mandibula_posterior',
                                    'paciente_jovem',
                                    'assintomatico',
                                    'sem_expansao'],
                         'moderados': ['unilocular', 'dentes_vitais', 'bem_delimitado'],
                         'incompativeis': ['radiopaco_puro',
                                           'grande_expansivo',
                                           'destruicao_cortical',
                                           'estruturas_dentiformes'],
                         'score_malignidade_esperado': 'muito_baixo'},
 'cisto_osseo_aneurismatico': {'grupo': 'pseudocisto',
                               'necessarios': ['radiolucido'],
                               'fortes': ['expansao_rapida',
                                          'multilocular',
                                          'insuflamento_cortical',
                                          'dor_leve_ou_intensa',
                                          'nivel_liquido_liquido'],
                               'moderados': ['paciente_jovem', 'mandibula_posterior', 'assimetria_facial'],
                               'incompativeis': ['radiopaco_puro',
                                                 'estruturas_dentiformes',
                                                 'sem_expansao',
                                                 'abaixo_canal_mandibular_sem_expansao'],
                               'score_malignidade_esperado': 'intermediario'},
 'osteomielite_cronica': {'grupo': 'infecciosa_ossea',
                          'necessarios': [],
                          'fortes': ['dor_intensa',
                                     'sinais_infecciosos',
                                     'sequestro_osseo',
                                     'periostite_reacional',
                                     'margem_mal_definida',
                                     'radiolucido_ou_misto'],
                          'moderados': ['fistula', 'febre', 'historia_extracao', 'diabetes'],
                          'incompativeis': ['estruturas_dentiformes',
                                            'bem_delimitado_corticalizado_assintomatico',
                                            'dente_incluso_pericoronario_tipico'],
                          'score_malignidade_esperado': 'intermediario'},
 'osteonecrose_medicamentosa': {'grupo': 'necrose_ossea',
                                'necessarios': ['uso_antirreabsortivo_ou_antiangiogenico'],
                                'fortes': ['osso_exposto',
                                           'dor_intensa',
                                           'sequestro_osseo',
                                           'misto_esclerotico_litico',
                                           'historia_extracao'],
                                'moderados': ['mandibula_posterior', 'fistula', 'infecao_secundaria'],
                                'incompativeis': ['paciente_sem_medicacao_risco',
                                                  'estruturas_dentiformes',
                                                  'pericoronario_dente_incluso'],
                                'score_malignidade_esperado': 'intermediario'},
 'tumor_marrom_hiperparatireoidismo': {'grupo': 'metabolica',
                                       'necessarios': ['hiperparatireoidismo_ou_alteracao_calcio_pth'],
                                       'fortes': ['radiolucido',
                                                  'multilocular',
                                                  'lesoes_multiplas',
                                                  'perda_lamina_dura',
                                                  'expansao_cortical'],
                                       'moderados': ['dor_leve', 'mandibula', 'historia_renal'],
                                       'incompativeis': ['radiopaco_puro',
                                                         'estruturas_dentiformes',
                                                         'lesao_unica_tipica_pericoronaria'],
                                       'score_malignidade_esperado': 'baixo_intermediario'},
 'osteossarcoma_gnatico': {'grupo': 'tumor_osseo_maligno',
                           'necessarios': [],
                           'fortes': ['margem_mal_definida',
                                      'destruicao_cortical',
                                      'crescimento_rapido',
                                      'reacao_periosteal_agressiva',
                                      'raios_de_sol',
                                      'triangulo_codman',
                                      'alargamento_espaco_periodontal',
                                      'perda_lamina_dura'],
                           'moderados': ['radiopaco_ou_misto',
                                         'dor_intensa',
                                         'parestesia',
                                         'mobilidade_dentaria',
                                         'invasao_partes_moles',
                                         'paciente_jovem',
                                         'mandibula_posterior'],
                           'incompativeis': ['bem_delimitado_corticalizado',
                                             'assintomatico_sem_sinais_agressivos',
                                             'dente_incluso_pericoronario_tipico',
                                             'estruturas_dentiformes'],
                           'score_malignidade_esperado': 'alto'},
 'metastase_ossea_gnatica': {'grupo': 'maligna_metastatica',
                             'necessarios': [],
                             'fortes': ['historico_oncologico',
                                        'margem_mal_definida',
                                        'destruicao_cortical',
                                        'dor_intensa',
                                        'parestesia',
                                        'crescimento_rapido',
                                        'lesoes_multiplas'],
                             'moderados': ['idade_maior_50',
                                           'mobilidade_dentaria',
                                           'invasao_partes_moles',
                                           'mandibula_posterior'],
                             'incompativeis': ['estruturas_dentiformes',
                                               'massa_radiopaca_irregular_com_halo',
                                               'assintomatico_sem_sinais_agressivos',
                                               'bem_delimitado_corticalizado'],
                             'score_malignidade_esperado': 'alto'},
 'mieloma_multiplo': {'grupo': 'maligna_hematologica',
                      'necessarios': [],
                      'fortes': ['lesoes_multiplas', 'punched_out', 'dor_ossea', 'idade_maior_50', 'radiolucido'],
                      'moderados': ['anemia', 'fratura_patologica', 'mandibula'],
                      'incompativeis': ['lesao_unica_pericoronaria',
                                        'estruturas_dentiformes',
                                        'radiopaco_puro',
                                        'paciente_jovem_assintomatico'],
                      'score_malignidade_esperado': 'alto'},
 'linfoma_osseo': {'grupo': 'maligna_hematologica',
                   'necessarios': [],
                   'fortes': ['margem_mal_definida',
                              'dor_intensa',
                              'parestesia',
                              'destruicao_cortical',
                              'aumento_volume_rapido',
                              'linfonodos'],
                   'moderados': ['radiolucido', 'mobilidade_dentaria', 'invasao_partes_moles'],
                   'incompativeis': ['estruturas_dentiformes', 'bem_delimitado_corticalizado', 'assintomatico'],
                   'score_malignidade_esperado': 'alto'},
 'defeito_osseo_stafne': {'grupo': 'variacao_anatomica',
                          'necessarios': ['radiolucido', 'unilocular', 'abaixo_canal_mandibular'],
                          'fortes': ['bem_delimitado',
                                     'corticalizado',
                                     'assintomatico',
                                     'sem_expansao',
                                     'posterior_mandibula'],
                          'moderados': ['homem_adulto', 'achado_incidental', 'lingual_mandibula'],
                          'incompativeis': ['grande_maior_40mm',
                                            'bolhas_de_sabao',
                                            'multilocular',
                                            'expansao_cortical',
                                            'destruicao_cortical',
                                            'dor_intensa',
                                            'parestesia'],
                          'score_malignidade_esperado': 'muito_baixo'},
 'histiocitose_celulas_langerhans': {'grupo': 'lesao_imunoproliferativa',
                                     'necessarios': [],
                                     'fortes': ['radiolucido',
                                                'dentes_flutuantes',
                                                'perda_ossea_alveolar',
                                                'paciente_crianca_adolescente',
                                                'dor_leve'],
                                     'moderados': ['lesoes_multiplas', 'mobilidade_dentaria', 'ulceracao_mucosa'],
                                     'incompativeis': ['radiopaco_puro',
                                                       'estruturas_dentiformes',
                                                       'bem_delimitado_corticalizado_pericoronario'],
                                     'score_malignidade_esperado': 'intermediario'}}
